In [1]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv("Your file path")

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
4915        NaN        NaN        NaN  
4916        NaN        NaN        NaN  
4917        NaN        NaN        NaN  
4918        NaN        NaN        NaN  
4919        NaN        NaN    

In [3]:
# Many NaN Values, print them for better understanding
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [4]:
# We Cannnot Simply Remove the Columns, thus replacing the NaN values with nothing
# Putting all Symptoms in 1 Column makes it easier to perform feature extraction, tokenisation etc
df = df.fillna("")
df['Symptom']=""
for i in range(1,18):
    df['s']=df["Symptom_{}".format(i)]
    df['Symptom']=df['Symptom']+df['s']
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches                                                     
1                                                                           
2                                                                           
3                                                                           
4                                                                           

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0                                                                     
1                                                                     
2                                                                     
3                                                                     
4                                                                     

  Symptom_16 Symptom_17                                            Symptom s  
0                        itching skin_rash nodal_skin_eruptions dischro...    
1                         skin_rash nodal_skin_eruptions dischromic _pa...    
2                         itching nodal_skin_eruptions dischromic _patches    
3                                    itching skin_rash dischromic _patches    
4                                   itching skin_rash nodal_skin_eruptions

In [5]:
for i in range(1,18):
    df=df.drop("Symptom_{}".format(i),axis=1)
df=df.drop("s",axis=1)
df.head()

Disease                                            Symptom
0  Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
1  Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
2  Fungal infection   itching nodal_skin_eruptions dischromic _patches
3  Fungal infection              itching skin_rash dischromic _patches
4  Fungal infection             itching skin_rash nodal_skin_eruptions

In [6]:
df[0:1].values

array([['Fungal infection',
        'itching skin_rash nodal_skin_eruptions dischromic _patches']],
      dtype=object)

In [7]:
df['Disease'].value_counts()

Disease
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Aller

we have a balanced data i.e. equal distribution across all classes

In [8]:
X=df['Disease']
Y=df['Symptom']
X.head(10),Y.head(10)

(0    Fungal infection
 1    Fungal infection
 2    Fungal infection
 3    Fungal infection
 4    Fungal infection
 5    Fungal infection
 6    Fungal infection
 7    Fungal infection
 8    Fungal infection
 9    Fungal infection
 Name: Disease, dtype: object,
 0    itching skin_rash nodal_skin_eruptions dischro...
 1     skin_rash nodal_skin_eruptions dischromic _pa...
 2     itching nodal_skin_eruptions dischromic _patches
 3                itching skin_rash dischromic _patches
 4               itching skin_rash nodal_skin_eruptions
 5     skin_rash nodal_skin_eruptions dischromic _pa...
 6     itching nodal_skin_eruptions dischromic _patches
 7                itching skin_rash dischromic _patches
 8               itching skin_rash nodal_skin_eruptions
 9    itching skin_rash nodal_skin_eruptions dischro...
 Name: Symptom, dtype: object)

In [9]:
# Splitting the Data into Train and Test datasets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.25,shuffle=True,random_state=44)
X_train.head(10)

1057        Hepatitis E
4480           Migraine
2394    Osteoarthristis
4467          Psoriasis
3525           Impetigo
3038      Drug Reaction
4906          Pneumonia
4131     Hypothyroidism
1405             Dengue
3033           Impetigo
Name: Disease, dtype: object

In [10]:
print('Training Data Shape:', Y_train.shape)
print('Testing Data Shape: ', Y_test.shape)

Training Data Shape: (3690,)
Testing Data Shape:  (1230,)


In [11]:
X_train.value_counts()

Disease
Jaundice                                   98
Migraine                                   98
hepatitis A                                95
Heart attack                               95
Dimorphic hemmorhoids(piles)               95
Allergy                                    95
Hepatitis C                                93
Hepatitis D                                93
Typhoid                                    92
Gastroenteritis                            92
Pneumonia                                  92
Hypoglycemia                               92
Common Cold                                91
Tuberculosis                               91
Fungal infection                           91
Hepatitis E                                91
Arthritis                                  91
Psoriasis                                  91
Peptic ulcer diseae                        91
Malaria                                    90
Bronchial Asthma                           90
Dengue                    

In [12]:
# Feature Extraction
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

Y_train_tfidf = vectorizer.fit_transform(Y_train)
Y_train_tfidf.shape

(3690, 135)

In [13]:
pd.DataFrame(Y_train_tfidf)[0]

0         (0, 107)\t0.42164632513477507\n  (0, 22)\t0....
1         (0, 124)\t0.4120490720427296\n  (0, 54)\t0.2...
2         (0, 79)\t0.4510419179046219\n  (0, 112)\t0.4...
3         (0, 51)\t0.45900352946016976\n  (0, 103)\t0....
4         (0, 131)\t0.5269244100190276\n  (0, 90)\t0.5...
                              ...                        
3685      (0, 67)\t0.5036364766736794\n  (0, 71)\t0.42...
3686      (0, 111)\t0.37930170238198424\n  (0, 65)\t0....
3687      (0, 87)\t0.6519490465239833\n  (0, 9)\t0.653...
3688      (0, 5)\t0.6339138832160964\n  (0, 128)\t0.65...
3689      (0, 39)\t0.556559575085783\n  (0, 82)\t0.556...
Name: 0, Length: 3690, dtype: object

In [14]:
# Train the model
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(Y_train_tfidf,X_train)

LinearSVC()

In [15]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf.fit(Y_train, X_train)  


predictions = text_clf.predict(Y_test)

In [16]:
from sklearn import metrics
print(metrics.confusion_matrix(X_test,predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]


In [17]:
print(metrics.classification_report(X_test,predictions)) 

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic cholestasis       1.00      1.00      1.00        31
                            Common Cold       1.00      1.00      1.00        29
                           

In [18]:
print(metrics.accuracy_score(X_test,predictions))

1.0


Accuracy is 100

In [19]:
# Example for using the trained model
input_symptoms = ["headache", "nausea", "blurred vision"]
processed_input = vectorizer.transform([" ".join(input_symptoms)])  # Adjust this based on the preprocessing steps
predicted_disease = clf.predict(processed_input)
print(f"The predicted disease is: {predicted_disease[0]}")

The predicted disease is: (vertigo) Paroymsal  Positional Vertigo


# DT

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

In [21]:
X = df['Symptom']
Y = df['Disease']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=44)
text_clf = Pipeline([('tfidf', TfidfVectorizer()),('clf', DecisionTreeClassifier(random_state=44)),])

In [22]:
text_clf.fit(X_train, Y_train)
predictions = text_clf.predict(X_test)

In [23]:
print(metrics.confusion_matrix(Y_test, predictions))
print(metrics.classification_report(Y_test, predictions))
print("Accuracy:", metrics.accuracy_score(Y_test, predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic chole

In [24]:
input_symptoms = ["headache nausea blurred vision"]
predicted_disease = text_clf.predict(input_symptoms)
print(f"The predicted disease is: {predicted_disease[0]}")

The predicted disease is: Hepatitis C


# Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [26]:
X = df['Symptom']
Y = df['Disease']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=44)

In [27]:
text_clf_rf = Pipeline([('tfidf', TfidfVectorizer()),('clf', RandomForestClassifier(random_state=44)),])

In [28]:
text_clf_rf.fit(X_train, Y_train)
predictions = text_clf_rf.predict(X_test)

In [29]:
print(metrics.confusion_matrix(Y_test, predictions))
print(metrics.classification_report(Y_test, predictions))
print("Accuracy:", metrics.accuracy_score(Y_test, predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic chole

In [30]:
input_symptoms = ["headache nausea blurred vision"]
predicted_disease = text_clf_rf.predict(input_symptoms)
print(f"The predicted disease is: {predicted_disease[0]}")

The predicted disease is: (vertigo) Paroymsal  Positional Vertigo


# Naive bayes

In [31]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

In [32]:
X = df['Symptom']
Y = df['Disease']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=44)

In [33]:
text_clf = Pipeline([('tfidf', TfidfVectorizer()),('clf', MultinomialNB()),])

In [34]:
text_clf.fit(X_train, Y_train)
predictions = text_clf.predict(X_test)

In [35]:
print(metrics.confusion_matrix(Y_test, predictions))
print(metrics.classification_report(Y_test, predictions))
print("Accuracy:", metrics.accuracy_score(Y_test, predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic chole

In [36]:
input_symptoms = ["headache nausea blurred vision"]
predicted_disease = text_clf.predict(input_symptoms)
print(f"The predicted disease is: {predicted_disease[0]}")

The predicted disease is: Malaria


In [47]:
import tkinter as tk
from tkinter import messagebox
import pickle  # To load your trained model
import numpy as np

with open("disease_model.pkl", "wb") as file:
    pickle.dump(text_clf_rf, file)

In [50]:
def predict_disease():
    try:
        # Retrieve and preprocess inputs from entry fields
        inputs = [entry.get().strip() for entry in entries]
        print("User inputs:", inputs)  # Debugging input values

        # Preprocess strings if needed
        inputs = [x.lower() for x in inputs]  # Example: Convert to lowercase
        
        # Convert to array
#         inputs_array = np.array(inputs).reshape(1, -1)
        print("Inputs array:", inputs)  # Debugging preprocessed array
        
        # Make prediction
        #         input_symptoms = ["headache nausea blurred vision"]
        predicted_disease = text_clf_rf.predict(inputs)
#         print(f"The predicted disease is: {predicted_disease[0]}")
        
#         prediction = text_clf.predict(inputs)
        messagebox.showinfo("Prediction Result", f"Predicted Diseases: {predicted_disease}")
    except Exception as e:
        messagebox.showerror("Error", f"An error occurred: {e}")

# Create main Tkinter window
root = tk.Tk()
root.title("Disease Prediction")
root.geometry("400x400")

# Define labels and entry fields for user input
labels = ["Symptom 1", "Symptom 2", "Symptom 3"]  # Update with actual feature names
entries = []

for idx, label_text in enumerate(labels):
    label = tk.Label(root, text=label_text, font=("Arial", 12))
    label.pack(pady=5)
    entry = tk.Entry(root, font=("Arial", 12))
    entry.pack(pady=5)
    entries.append(entry)

# Prediction Button
predict_button = tk.Button(root, text="Predict", command=predict_disease, font=("Arial", 14), bg="blue", fg="white")
predict_button.pack(pady=20)

# Run the Tkinter event loop
root.mainloop()


User inputs: ['acidity', 'cough', 'vomitting']
Inputs array: ['acidity', 'cough', 'vomitting']
