In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"Your file path")
df

Name DateOfBirth  Gender                    Symptoms  \
0       John Doe  15-05-1980    Male                Fever, Cough   
1     Jane Smith  10-08-1992  Female           Headache, Fatigue   
2    Michael Lee  20-02-1975    Male         Shortness of breath   
3     Emily Chen  03-11-1988  Female            Nausea, Vomiting   
4      Alex Wong  12-06-2001    Male                 Sore Throat   
..           ...         ...     ...                         ...   
282      Ava Lim  11-07-1993  Female  Cough, Shortness of breath   
283     Liam Goh  16-09-1987    Male            Itching, Redness   
284   Sophie Tan  18-02-1975  Female        Muscle Pain, Fatigue   
285     Noah Lim  21-05-2005    Male            Nausea, Vomiting   
286    Ella Wong  05-10-1999  Female    Headache, Blurred Vision   

                   Causes               Disease               Medicine  
0         Viral Infection           Common Cold        Ibuprofen, Rest  
1                  Stress              Migraine            Sumatriptan  
2               Pollution                Asthma      Albuterol Inhaler  
3          Food Poisoning       Gastroenteritis       Oral Rehydration  
4     Bacterial Infection          Strep Throat             Penicillin  
..                    ...                   ...                    ...  
282  COVID-19 Exposure           COVID-19            Isolation, Fluids  
283  Allergies             Allergic Reaction An            tihistamine  
284  Overexertion               Muscle Strain     Rest, Pain Relievers  
285      Food Poisoning         Muscle Strain              Rehydration  
286  Eye Strain                 Muscle Strain            Eye Exercises  

[287 rows x 7 columns]

In [3]:
df.columns

Index(['Name', 'DateOfBirth', 'Gender', 'Symptoms', 'Causes', 'Disease',
       'Medicine'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Name         241 non-null    object
 1   DateOfBirth  241 non-null    object
 2   Gender       242 non-null    object
 3   Symptoms     247 non-null    object
 4   Causes       245 non-null    object
 5   Disease      249 non-null    object
 6   Medicine     242 non-null    object
dtypes: object(7)
memory usage: 15.8+ KB


In [5]:
df.isnull().sum()

Name           46
DateOfBirth    46
Gender         45
Symptoms       40
Causes         42
Disease        38
Medicine       45
dtype: int64

In [6]:
missing_values = df.isnull().sum()

In [7]:
df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'], errors='coerce')
median_date = df['DateOfBirth'].dropna().median()
df['DateOfBirth'].fillna(median_date, inplace=True)
categorical_columns = ['Gender', 'Symptoms', 'Causes', 'Disease', 'Medicine']
for column in categorical_columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

C:\Users\ragha\AppData\Local\Temp\ipykernel_25156\3951433367.py:1: UserWarning: Parsing '15-05-1980' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'], errors='coerce')
C:\Users\ragha\AppData\Local\Temp\ipykernel_25156\3951433367.py:1: UserWarning: Parsing '20-02-1975' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'], errors='coerce')
C:\Users\ragha\AppData\Local\Temp\ipykernel_25156\3951433367.py:1: UserWarning: Parsing '25-03-1972' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'], errors='coerce')
C:\Users\ragha\AppData\Local\Temp\ipykernel_25156\3951433367.py:1: UserWarning: Parsing '18-09-1995' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for c

In [8]:
df.isnull().sum()

Name           46
DateOfBirth     0
Gender          0
Symptoms        0
Causes          0
Disease         0
Medicine        0
dtype: int64

In [9]:
df['Name'].fillna('Unknown', inplace=True)

In [10]:
df.isnull().sum()

Name           0
DateOfBirth    0
Gender         0
Symptoms       0
Causes         0
Disease        0
Medicine       0
dtype: int64

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [12]:
df[0:1].values

array([['John Doe', Timestamp('1980-05-15 00:00:00'), 'Male',
        'Fever, Cough', 'Viral Infection', 'Common Cold',
        'Ibuprofen, Rest']], dtype=object)

In [13]:
X = df['Medicine']
Y = df['Symptoms']
X.head(10), Y.head(10)

(0      Ibuprofen, Rest
 1          Sumatriptan
 2    Albuterol Inhaler
 3     Oral Rehydration
 4           Penicillin
 5               NSAIDs
 6           Amlodipine
 7        Antihistamine
 8             Antacids
 9           Sertraline
 Name: Medicine, dtype: object,
 0                Fever, Cough
 1           Headache, Fatigue
 2         Shortness of breath
 3            Nausea, Vomiting
 4                 Sore Throat
 5         Joint Pain, Fatigue
 6       Chest Pain, Dizziness
 7            Itching, Redness
 8    Abdominal Pain, Bloating
 9            Fatigue, Sadness
 Name: Symptoms, dtype: object)

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.25,shuffle=True,random_state=44)
X_train.head(10)

218         Rest, Lifestyle
23             CPAP Machine
48         Rest, Stretching
5                    NSAIDs
211         Rest, Lifestyle
39     Rest, Pain Relievers
3          Oral Rehydration
95             Fluids, Rest
196        Oral Rehydration
87        Antibiotics, Rest
Name: Medicine, dtype: object

In [15]:
print('Training Data Shape:', Y_train.shape)
print('Testing Data Shape: ', Y_test.shape)

Training Data Shape: (215,)
Testing Data Shape:  (72,)


In [16]:
X_train.value_counts()

Rest, Lifestyle            47
NSAIDs                     11
Rest, Stretching            9
Oral Rehydration            9
Rest, Eye Exercises         8
Pain Relievers, PT          7
Rest, Pain Relievers        7
Fluids, Rest                7
Antibiotics, Rest           6
Dimenhydrinate              6
Fluids, Bland Diet          6
Therapy, Medication         5
Antacids                    5
Topical Steroids            5
Isolation, Fluids           5
Penicillin                  5
CPAP Machine                4
Pain Relievers              4
Relaxation, NSAIDs          4
Antihistamine               4
Iron Supplements            4
Levothyroxine               3
Cognitive Therapy           3
 Antihistamine              2
Nitroglycerin,Aspirin       2
Sumatriptan                 2
on   Antihistamine          2
 Therapy, Medication        2
Hydration, Rest             2
Amlodipine                  2
Antivirals, Rest            2
  Rest, Lifestyle           1
 Rest, Pain Relievers       1
  Levothyr

# LinearSVC

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

Y_train_tfidf = vectorizer.fit_transform(Y_train)
Y_train_tfidf.shape

(215, 44)

In [18]:
pd.DataFrame(Y_train_tfidf)[0]

0        (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
1        (0, 8)\t0.5901391638127799\n  (0, 27)\t0.567...
2        (0, 28)\t0.32747998470009276\n  (0, 10)\t0.5...
3        (0, 23)\t0.7634320868466464\n  (0, 28)\t0.47...
4        (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
                             ...                        
210      (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
211      (0, 32)\t0.7431304281799951\n  (0, 22)\t0.66...
212      (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
213      (0, 8)\t0.720999388782707\n  (0, 27)\t0.6929...
214      (0, 13)\t0.8316833684814849\n  (0, 25)\t0.55...
Name: 0, Length: 215, dtype: object

In [19]:
# Train the model
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(Y_train_tfidf,X_train)

LinearSVC()

In [20]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf.fit(Y_train, X_train)  


predictions = text_clf.predict(Y_test)

In [21]:
from sklearn import metrics
print(metrics.confusion_matrix(X_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
print(metrics.classification_report(X_test,predictions)) 

                      precision    recall  f1-score   support

      Dimenhydrinate       0.00      0.00      0.00         2
     Hydration, Rest       0.00      0.00      0.00         1
      Pain Relievers       0.00      0.00      0.00         0
          Sertraline       0.00      0.00      0.00         1
   Albuterol Inhaler       0.00      0.00      0.00         2
            Antacids       0.67      1.00      0.80         2
   Antibiotics, Rest       1.00      1.00      1.00         6
       Antihistamine       1.00      1.00      1.00         3
    Antivirals, Rest       0.67      1.00      0.80         2
        CPAP Machine       0.33      1.00      0.50         1
   Cognitive Therapy       1.00      1.00      1.00         2
      Dimenhydrinate       0.60      1.00      0.75         3
  Fluids, Bland Diet       1.00      1.00      1.00         2
        Fluids, Rest       1.00      1.00      1.00         3
  Ginger, Vitamin B6       0.00      0.00      0.00         1
       

C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_cla

In [23]:
print(metrics.accuracy_score(X_test,predictions))

0.7777777777777778


In [24]:
input_symptoms = ["Muscle Pain, Fatigue"]
processed_input = vectorizer.transform([" ".join(input_symptoms)])  # Adjust this based on the preprocessing steps
recommended_medicine = clf.predict(processed_input)
print(f"The recommended medicine is: {recommended_medicine[0]}")

The recommended medicine is: Rest, Pain Relievers


# Naive Bayes

In [25]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [26]:
text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),('clf', MultinomialNB()),])

In [27]:
text_clf_nb.fit(Y_train, X_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [28]:
predictions_nb = text_clf_nb.predict(Y_test)

In [29]:
print("Confusion Matrix:")
print(metrics.confusion_matrix(X_test, predictions_nb))
print("\nClassification Report:")
print(metrics.classification_report(X_test, predictions_nb)) 
print("Accuracy Score:", metrics.accuracy_score(X_test, predictions_nb))

Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Classification Report:
                      precision    recall  f1-score   support

      Dimenhydrinate       0.00      0.00      0.00         2
     Hydration, Rest       0.00      0.00      0.00         1
          Sertraline       0.00      0.00      0.00         1
   Albuterol Inhaler       0.00      0.00      0.00         2
            Antacids       0.67      1.00      0.80         2
   Antibiotics, Rest       1.00      1.00      1.00         6
       Antihistamine       1.00      1.00      1.00         3
    Antivirals, Rest       0.00      0.00      0.00         2
        CPAP Machine       0.00      0.00      0.00         1
   Cognitive Therapy       1.00      1.00      1.00         2
      Dimenhydrinate       0.60      1.00      0.75         3
  Fluids, Bland Diet       1.00      1.00      1.00         2
        Fluids, Rest       0.50

C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
input_symptoms = ["Fever, Cough	"]
processed_input_nb = vectorizer.transform([" ".join(input_symptoms)])
recommended_medicine_nb = text_clf_nb.predict(input_symptoms)
print(f"The recommended medicine is: {recommended_medicine_nb[0]}")


The recommended medicine is: Fluids, Rest


# Randomforest

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [32]:
text_clf_rf = Pipeline([('tfidf', TfidfVectorizer()),('clf', RandomForestClassifier(n_estimators=100, random_state=42)),])

In [33]:
text_clf_rf.fit(Y_train, X_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier(random_state=42))])

In [34]:
predictions_rf = text_clf_rf.predict(Y_test)

In [35]:
print("Confusion Matrix:")
print(metrics.confusion_matrix(X_test, predictions_rf))
print("\nClassification Report:")
print(metrics.classification_report(X_test, predictions_rf)) 
print("Accuracy Score:", metrics.accuracy_score(X_test, predictions_rf))

Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Classification Report:
                      precision    recall  f1-score   support

      Dimenhydrinate       0.00      0.00      0.00         2
     Hydration, Rest       0.00      0.00      0.00         1
          Sertraline       0.00      0.00      0.00         1
   Albuterol Inhaler       0.00      0.00      0.00         2
            Antacids       0.67      1.00      0.80         2
   Antibiotics, Rest       1.00      1.00      1.00         6
       Antihistamine       1.00      1.00      1.00         3
    Antivirals, Rest       0.50      1.00      0.67         2
        CPAP Machine       0.33      1.00      0.50         1
   Cognitive Therapy       1.00      1.00      1.00         2
      Dimenhydrinate       0.60      1.00      0.75         3
  Fluids, Bland Diet       1.00      1.00      1.00         2
        Fluids, Rest       1.00

C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
input_symptoms = ["Abdominal Pain, Bloating O"]
recommended_medicine_rf = text_clf_rf.predict(input_symptoms)
print(f"The recommended medicine using Random Forest is: {recommended_medicine_rf[0]}")

The recommended medicine using Random Forest is: Antacids


In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

In [45]:
X = df['Symptoms']
Y = df['Medicine']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=44)

In [46]:
text_clf = Pipeline([('tfidf', TfidfVectorizer()),('clf', DecisionTreeClassifier(random_state=44)),])

In [47]:
text_clf.fit(X_train, Y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', DecisionTreeClassifier(random_state=44))])

In [48]:
predictions = text_clf.predict(X_test)

In [49]:
from sklearn import metrics
print(metrics.confusion_matrix(Y_test, predictions))
print(metrics.classification_report(Y_test, predictions))
print("Accuracy:", metrics.accuracy_score(Y_test, predictions))

[[ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0

C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [51]:
input_symptoms = ["Itching, Redness"]
recommended_medicine = text_clf.predict(input_symptoms)
print(f"The recommended medicine is: {recommended_medicine[0]}")

The recommended medicine is: Antihistamine
