In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC  # Import SVM
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [2]:
# Load the dataset
df = pd.read_csv(r"C:\\Users\\HP\\OneDrive\\Documents\\minor_srm\\disease_dataset.csv")
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df = df.fillna("")
df['Symptom']=""
for i in range(1,18):
    df['s']=df["Symptom_{}".format(i)]
    df['Symptom']=df['Symptom']+df['s']
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches                                                     
1                                                                           
2                                                                           
3                                                                           
4                                                                           

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0                                                                     
1                                                                     
2                                                                     
3                                                                     
4                                                                     

  Symptom_16 Symptom_17                                            Symptom s  
0                        itching skin_rash nodal_skin_eruptions dischro...    
1                         skin_rash nodal_skin_eruptions dischromic _pa...    
2                         itching nodal_skin_eruptions dischromic _patches    
3                                    itching skin_rash dischromic _patches    
4                                   itching skin_rash nodal_skin_eruptions

In [4]:
for i in range(1,18):
    df=df.drop("Symptom_{}".format(i),axis=1)
df=df.drop("s",axis=1)
df.head()

Disease                                            Symptom
0  Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
1  Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
2  Fungal infection   itching nodal_skin_eruptions dischromic _patches
3  Fungal infection              itching skin_rash dischromic _patches
4  Fungal infection             itching skin_rash nodal_skin_eruptions

In [5]:
X=df['Disease']
Y=df['Symptom']
X.head(10),Y.head(10)

(0    Fungal infection
 1    Fungal infection
 2    Fungal infection
 3    Fungal infection
 4    Fungal infection
 5    Fungal infection
 6    Fungal infection
 7    Fungal infection
 8    Fungal infection
 9    Fungal infection
 Name: Disease, dtype: object,
 0    itching skin_rash nodal_skin_eruptions dischro...
 1     skin_rash nodal_skin_eruptions dischromic _pa...
 2     itching nodal_skin_eruptions dischromic _patches
 3                itching skin_rash dischromic _patches
 4               itching skin_rash nodal_skin_eruptions
 5     skin_rash nodal_skin_eruptions dischromic _pa...
 6     itching nodal_skin_eruptions dischromic _patches
 7                itching skin_rash dischromic _patches
 8               itching skin_rash nodal_skin_eruptions
 9    itching skin_rash nodal_skin_eruptions dischro...
 Name: Symptom, dtype: object)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.25,shuffle=True,random_state=44)

In [7]:
vectorizer = TfidfVectorizer()

Y_train_tfidf = vectorizer.fit_transform(Y_train)
Y_train_tfidf.shape

(3690, 135)

In [8]:
pd.DataFrame(Y_train_tfidf)[0]

0         (0, 107)\t0.42164632513477507\n  (0, 22)\t0....
1         (0, 124)\t0.4120490720427296\n  (0, 54)\t0.2...
2         (0, 79)\t0.4510419179046219\n  (0, 112)\t0.4...
3         (0, 51)\t0.45900352946016976\n  (0, 103)\t0....
4         (0, 131)\t0.5269244100190276\n  (0, 90)\t0.5...
                              ...                        
3685      (0, 67)\t0.5036364766736794\n  (0, 71)\t0.42...
3686      (0, 111)\t0.37930170238198424\n  (0, 65)\t0....
3687      (0, 87)\t0.6519490465239833\n  (0, 9)\t0.653...
3688      (0, 5)\t0.6339138832160964\n  (0, 128)\t0.65...
3689      (0, 39)\t0.556559575085783\n  (0, 82)\t0.556...
Name: 0, Length: 3690, dtype: object

In [9]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(Y_train_tfidf,X_train)

LinearSVC()

In [10]:
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf.fit(Y_train, X_train)  


predictions = text_clf.predict(Y_test)

In [11]:
print(metrics.confusion_matrix(X_test,predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]


In [12]:
print(metrics.classification_report(X_test,predictions))
print(metrics.accuracy_score(X_test,predictions))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic cholestasis       1.00      1.00      1.00        31
                            Common Cold       1.00      1.00      1.00        29
                           

In [13]:
input_symptoms = ["headache", "nausea", "blurred vision"]
processed_input = vectorizer.transform([" ".join(input_symptoms)])  # Adjust this based on the preprocessing steps
predicted_disease = clf.predict(processed_input)
print(f"The predicted disease is: {predicted_disease[0]}")

The predicted disease is: (vertigo) Paroymsal  Positional Vertigo


In [14]:
print(input_symptoms)

['headache', 'nausea', 'blurred vision']


# RF

In [15]:
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.pipeline import Pipeline

In [16]:
# X = df['Symptom']
# Y = df['Disease']
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=44)

In [17]:
# text_clf_r = Pipeline([('tfidf', TfidfVectorizer()),('clf', RandomForestClassifier(random_state=44)),])

In [18]:
# text_clf_r.fit(X_train, Y_train)
# predictions = text_clf.predict(X_test)

In [19]:
# print(metrics.confusion_matrix(Y_test, predictions))
# print(metrics.classification_report(Y_test, predictions))
# print("Accuracy:", metrics.accuracy_score(Y_test, predictions))

In [20]:
# input_symptoms = ["headache nausea blurred vision"]
# predicted_disease = text_clf_r.predict(input_symptoms)
# print(f"The predicted disease is: {predicted_disease[0]}")
# input_medicine = predicted_disease

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import accuracy_score

# # Sample dataset
# data = {
#     'disease': ['Disease1', 'Disease2', 'Disease1', 'Disease3'],
#     'symptoms': ['itching, skin_rash, fever', 'fever, cough', 'itching, skin_rash', 'cough, fever']
# }

# # Convert to DataFrame
# df = pd.DataFrame(data)

# Split the 'symptoms' column into a list of symptoms
df['Symptom'] = df['Symptom'].apply(lambda x: x.split(', '))

# Use MultiLabelBinarizer to encode the symptoms as binary features
mlb = MultiLabelBinarizer()
symptom_matrix = mlb.fit_transform(df['Symptom'])

# Convert the symptom matrix to a DataFrame
symptom_df = pd.DataFrame(symptom_matrix, columns=mlb.classes_)

# Merge the symptoms with the disease column
X = symptom_df
y = df['Disease']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest classifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Example of predicting for new symptoms
new_symptoms = ['itching', 'fever']
new_data = mlb.transform([new_symptoms])
new_prediction = model.predict(new_data)
print(f"Predicted Disease: {new_prediction[0]}")


Model Accuracy: 1.00
Predicted Disease: Dengue


C:\Users\HP\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:895: UserWarning: unknown class(es) ['fever', 'itching'] will be ignored
  warnings.warn(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import accuracy_score

# # Sample dataset
# data = {
#     'disease': ['Disease1', 'Disease2', 'Disease1', 'Disease3'],
#     'symptoms': [['itching', 'skin_rash', 'fever'], ['fever', 'cough'], ['itching', 'skin_rash'], ['cough', 'fever']]
# }

# # Convert to DataFrame
# df = pd.DataFrame(data)

# Use MultiLabelBinarizer to encode the symptoms as binary features
mlb = MultiLabelBinarizer()
symptom_matrix = mlb.fit_transform(df['Symptom'])

# Convert the symptom matrix to a DataFrame with the same column names as the training data
symptom_df = pd.DataFrame(symptom_matrix, columns=mlb.classes_)

# Merge the symptoms with the disease column
X = symptom_df
y = df['Disease']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest classifier
model_r = RandomForestClassifier(random_state=42)
model_r.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Example of predicting for new symptoms
new_symptoms = ['itching', 'fever']

# Transform the new symptoms using the same MultiLabelBinarizer that was used during training
new_data = mlb.transform([new_symptoms])

# Ensure the new data has the same feature names as the training data
new_data_df = pd.DataFrame(new_data, columns=mlb.classes_)

# Predict the disease for the new symptoms
new_prediction = model.predict(new_data_df)
print(f"Predicted Disease: {new_prediction[0]}")


Model Accuracy: 1.00
Predicted Disease: Dengue


C:\Users\HP\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:895: UserWarning: unknown class(es) ['fever', 'itching'] will be ignored
  warnings.warn(


# DT

In [23]:
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.pipeline import Pipeline
# X = df['Symptom']
# Y = df['Disease']
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=44)
# text_clf_dt = Pipeline([('tfidf', TfidfVectorizer()),('clf', DecisionTreeClassifier(random_state=44)),])
# text_clf_dt.fit(X_train, Y_train)
# predictions = text_clf.predict(X_test)


# medication

In [24]:
data = pd.read_csv(r"C:\\Users\\HP\\OneDrive\\Documents\\minor_srm\\medicaldata.csv")
data.head()

Name DateOfBirth  Gender             Symptoms               Causes  \
0     John Doe  15-05-1980    Male         Fever, Cough      Viral Infection   
1   Jane Smith  10-08-1992  Female    Headache, Fatigue               Stress   
2  Michael Lee  20-02-1975    Male  Shortness of breath            Pollution   
3   Emily Chen  03-11-1988  Female     Nausea, Vomiting       Food Poisoning   
4    Alex Wong  12-06-2001    Male          Sore Throat  Bacterial Infection   

           Disease           Medicine  
0      Common Cold    Ibuprofen, Rest  
1         Migraine        Sumatriptan  
2           Asthma  Albuterol Inhaler  
3  Gastroenteritis   Oral Rehydration  
4     Strep Throat         Penicillin

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Name         241 non-null    object
 1   DateOfBirth  241 non-null    object
 2   Gender       242 non-null    object
 3   Symptoms     247 non-null    object
 4   Causes       245 non-null    object
 5   Disease      249 non-null    object
 6   Medicine     242 non-null    object
dtypes: object(7)
memory usage: 15.8+ KB


In [26]:
data.isnull().sum()

Name           46
DateOfBirth    46
Gender         45
Symptoms       40
Causes         42
Disease        38
Medicine       45
dtype: int64

In [27]:
missing_values = data.isnull().sum()
data['DateOfBirth'] = pd.to_datetime(data['DateOfBirth'], errors='coerce')
median_date = data['DateOfBirth'].dropna().median()
data['DateOfBirth'].fillna(median_date, inplace=True)
categorical_columns = ['Gender', 'Symptoms', 'Causes', 'Disease', 'Medicine']
for column in categorical_columns:
    data[column].fillna(data[column].mode()[0], inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_2028\3982565634.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['DateOfBirth'] = pd.to_datetime(data['DateOfBirth'], errors='coerce')


In [28]:
data['Name'].fillna('Unknown', inplace=True)

In [29]:
data.isnull().sum()

Name           0
DateOfBirth    0
Gender         0
Symptoms       0
Causes         0
Disease        0
Medicine       0
dtype: int64

In [30]:
X_medicine = data['Medicine']
Y_medicine = data['Symptoms']
X_train_medicine, X_test_medicine, Y_train_medicine, Y_test_medicine = train_test_split(X_medicine, Y_medicine, test_size=0.25, shuffle=True, random_state=44)
X_train_medicine.head(10)
X_train_medicine.value_counts()

Medicine
Rest, Lifestyle            47
NSAIDs                     11
Rest, Stretching            9
Oral Rehydration            9
Rest, Eye Exercises         8
Pain Relievers, PT          7
Rest, Pain Relievers        7
Fluids, Rest                7
Antibiotics, Rest           6
Dimenhydrinate              6
Fluids, Bland Diet          6
Therapy, Medication         5
Antacids                    5
Topical Steroids            5
Isolation, Fluids           5
Penicillin                  5
CPAP Machine                4
Pain Relievers              4
Relaxation, NSAIDs          4
Antihistamine               4
Iron Supplements            4
Levothyroxine               3
Cognitive Therapy           3
 Antihistamine              2
Nitroglycerin,Aspirin       2
Sumatriptan                 2
on   Antihistamine          2
 Therapy, Medication        2
Hydration, Rest             2
Amlodipine                  2
Antivirals, Rest            2
  Rest, Lifestyle           1
 Rest, Pain Relievers       1
 

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

Y_train_medicine_tfidf = vectorizer.fit_transform(Y_train_medicine)
Y_train_medicine_tfidf.shape

(215, 44)

In [32]:
pd.DataFrame(Y_train_medicine_tfidf)[0]

0        (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
1        (0, 8)\t0.5901391638127799\n  (0, 27)\t0.567...
2        (0, 28)\t0.32747998470009276\n  (0, 10)\t0.5...
3        (0, 23)\t0.7634320868466464\n  (0, 28)\t0.47...
4        (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
                             ...                        
210      (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
211      (0, 32)\t0.7431304281799951\n  (0, 22)\t0.66...
212      (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
213      (0, 8)\t0.720999388782707\n  (0, 27)\t0.6929...
214      (0, 13)\t0.8316833684814849\n  (0, 25)\t0.55...
Name: 0, Length: 215, dtype: object

In [33]:
pd.DataFrame(Y_train_medicine_tfidf)[0]

0        (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
1        (0, 8)\t0.5901391638127799\n  (0, 27)\t0.567...
2        (0, 28)\t0.32747998470009276\n  (0, 10)\t0.5...
3        (0, 23)\t0.7634320868466464\n  (0, 28)\t0.47...
4        (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
                             ...                        
210      (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
211      (0, 32)\t0.7431304281799951\n  (0, 22)\t0.66...
212      (0, 43)\t0.7633059160515471\n  (0, 18)\t0.64...
213      (0, 8)\t0.720999388782707\n  (0, 27)\t0.6929...
214      (0, 13)\t0.8316833684814849\n  (0, 25)\t0.55...
Name: 0, Length: 215, dtype: object

In [34]:
from sklearn.pipeline import Pipeline
text_clf_m = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf_m.fit(Y_train_medicine, X_train_medicine)  


predictions = text_clf_m.predict(Y_test_medicine)

In [35]:
from sklearn import metrics
print(metrics.confusion_matrix(X_test_medicine,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
print(metrics.classification_report(X_test_medicine,predictions)) 

                      precision    recall  f1-score   support

      Dimenhydrinate       0.00      0.00      0.00         2
     Hydration, Rest       0.00      0.00      0.00         1
          Sertraline       0.00      0.00      0.00         1
   Albuterol Inhaler       0.00      0.00      0.00         2
            Antacids       0.67      1.00      0.80         2
   Antibiotics, Rest       1.00      1.00      1.00         6
       Antihistamine       1.00      1.00      1.00         3
    Antivirals, Rest       0.67      1.00      0.80         2
        CPAP Machine       0.33      1.00      0.50         1
   Cognitive Therapy       1.00      1.00      1.00         2
      Dimenhydrinate       0.60      1.00      0.75         3
  Fluids, Bland Diet       1.00      1.00      1.00         2
        Fluids, Rest       1.00      1.00      1.00         3
  Ginger, Vitamin B6       0.00      0.00      0.00         1
         Honey, Rest       0.00      0.00      0.00         1
     Hy

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
print(metrics.accuracy_score(X_test_medicine,predictions))

0.8055555555555556


In [38]:
# processed_input = vectorizer.transform([" ".join(input_symptoms)])  # Adjust this based on the preprocessing steps
# recommended_medicine = clf.predict(processed_input)
# print(f"The recommended medicine is: {recommended_medicine[0]}")

ValueError: X has 44 features, but LinearSVC is expecting 135 features as input.

In [39]:
import tkinter as tk
from tkinter import messagebox
import pickle  # To load your trained model
import numpy as np

with open("disease_model.pkl", "wb") as file:
    pickle.dump(text_clf, file)
    
with open("disease_model_med.pkl", "wb") as file:
    pickle.dump(text_clf_m, file)

In [40]:
def predict_disease():
    try:
        # Retrieve and preprocess inputs from entry fields
        inputs = [entry.get().strip() for entry in entries]
        print("User inputs:", inputs)  # Debugging input values

        # Preprocess strings if needed
        inputs = [x.lower() for x in inputs]  # Example: Convert to lowercase
        
        # Convert to array
#         inputs_array = np.array(inputs).reshape(1, -1)
        print("Inputs array:", inputs)  # Debugging preprocessed array
        
        # Make prediction
        #         input_symptoms = ["headache nausea blurred vision"]
        predicted_disease = text_clf.predict(inputs)
        recommended_medicine = text_clf_m.predict(inputs)
#         print(f"The predicted disease is: {predicted_disease[0]}")
        
#         prediction = text_clf.predict(inputs)
        messagebox.showinfo("Prediction Result", f"Predicted Disease: {predicted_disease[0]}")
        messagebox.showinfo("Prediction Result", f"Recommended Medicines/ Precautions: {recommended_medicine[0]}")
    
    except Exception as e:
        messagebox.showerror("Error", f"An error occurred: {e}")

from PIL import Image, ImageTk

# Initialize the Tkinter root window
root = tk.Tk()
root.title("Disease Prediction")
root.geometry("950x400")  # Adjust the size as needed

# Add an image at the top of the GUI
image_ref = None

# Add an image at the top of the GUI
def add_image():
    global image_ref  # Ensure the image object is not garbage collected
    # Load the image using PIL
    try:
        img = Image.open("C:\\Users\\HP\\OneDrive\\Documents\\minor_srm\\disease_img.webp")  # Replace with your image path
        img = img.resize((300, 150), Image.Resampling.LANCZOS)  # Resize the image to fit the top area
        image_ref = ImageTk.PhotoImage(img)

        # Create a label to display the image
        img_label = tk.Label(root, image=image_ref)
        img_label.pack(pady=10)  # Add some padding for spacing
    except Exception as e:
        print(f"Error loading image: {e}")

# Call the function to add the image
add_image()
# Define labels and entry fields for user input
labels = [
    "Symptom 1", "Symptom 2", "Symptom 3", "Symptom 4", "Symptom 5",
    "Symptom 6", "Symptom 7", "Symptom 8", "Symptom 9", "Symptom 10"
]  # Update with actual feature names

entries = []

# Create a frame to organize the grid layout
frame = tk.Frame(root)
frame.pack(padx=10, pady=10)

# Add labels and entry fields in a grid
for idx, label_text in enumerate(labels):
    row, col = divmod(idx, 5)  # Change 5 to the number of columns you prefer
    label = tk.Label(frame, text=label_text, font=("Arial", 12))
    label.grid(row=row * 2, column=col, padx=5, pady=5, sticky="w")
    entry = tk.Entry(frame, font=("Arial", 12))
    entry.grid(row=row * 2 + 1, column=col, padx=5, pady=5, sticky="w")
    entries.append(entry)

# Prediction Button
predict_button = tk.Button(root, text="Predict", command=predict_disease, font=("Arial", 14), bg="blue", fg="white")
predict_button.pack(pady=20)

# Run the Tkinter event loop
root.mainloop()


User inputs: ['cough', 'fever', '', '', '', '', '', '', '', '']
Inputs array: ['cough', 'fever', '', '', '', '', '', '', '', '']
User inputs: ['fever', 'chills', '', '', '', '', '', '', '', '']
Inputs array: ['fever', 'chills', '', '', '', '', '', '', '', '']
User inputs: ['fever', 'headache', 'fatigue', '', '', '', '', '', '', '']
Inputs array: ['fever', 'headache', 'fatigue', '', '', '', '', '', '', '']
User inputs: ['fatigue', 'headache', 'fever', '', '', '', '', '', '', '']
Inputs array: ['fatigue', 'headache', 'fever', '', '', '', '', '', '', '']
User inputs: ['fatigue', 'headache', '', '', '', '', '', '', '', '']
Inputs array: ['fatigue', 'headache', '', '', '', '', '', '', '', '']
User inputs: ['', 'headache', '', '', '', '', '', '', '', '']
Inputs array: ['', 'headache', '', '', '', '', '', '', '', '']
User inputs: ['chest pain', 'breathlessness', '', '', '', '', '', '', '', '']
Inputs array: ['chest pain', 'breathlessness', '', '', '', '', '', '', '', '']
User inputs: ['chest'